### ISSUE TITLE
Creating ids that follows a pattern

### ISSUE THREAD

**Issue by alejandrofdez-us** [dylang/shortid#127]
I would like to create SKUs that follows the pattern: /\w{2}-\w{4}/
(two letters followed by '-' and four letters).

Would it be possible with shortid?

Thanks in advance

**Comment by ai** [comment]
Nope, since shortid has dynamic ID length.

What you can do

1. Take Nano ID https://github.com/ai/nanoid
2. Check that 6 letters will not have collisions in your case https://alex7kom.github.io/nano-nanoid-cc/
3. Use `nanoid/generate` with custom alphabet and 6 symbols. Then use RegExp to put `-` inside.
