### ISSUE TITLE
Preventing start from number

### ISSUE THREAD

**Issue by ua9msn** [dylang/shortid#131]
How to prevent generating id which starts from a number? 
If i generate an ID for DOM element - this is required.

**Comment by ai** [comment]
1. `shortid` is not supported anymore. Use [Nano ID](https://github.com/ai/nanoid). It’s smaller and faster.
2. We can’t prevent start from the number by default, because it will affect security (by changing ID distribution). But you may create some `nanoid-html-id` package, which will have:

```js
while (true) {
  let id = nanoid()
  if (!/^\d/.test(id)) return id
}
```

If you will create this package, I will help you and promote it.
