### ISSUE TITLE
may generate invalid HTML id values

### ISSUE THREAD

**Issue by bcullman** [dylang/shortid#138]
per the HTML specification here: https://www.w3.org/TR/html4/types.html#type-id

ID and Name tokens *MUST* begin with a letter ([A-Za-z])

Numbers are still valid for IDs, just not as the first character.

**Comment by ai** [comment]
1. This project is deprecated don’t use it. Use [Nano ID](https://github.com/ai/nanoid)
2. For HTML ids use non-digits alphabet or put a letter on the beginning of ID `id = 'id' + nanoid()`

I can’t remove numbers from the begging of ID in Nano ID, since it will change symbols distribution and ID will not be secure anymore.
