### ISSUE TITLE
salt vs. seed?

### ISSUE THREAD

**Issue by chovy** [dylang/shortid#19]
This seems like its more of a salt (reused across entire app) rather than a seed (changed on every invocation).

**Comment by jamesrom** [comment]
I disagree with @chovy. It **is** a seed for the RNG, and definitely not a salt.

Salt is used as additional input to a hash function, and since shortid does not offer any way to hash a given input, it doesn't make sense to use the term 'salt' here.

Also, the [seed is updated](https://github.com/dylang/shortid/blob/master/lib/random.js#L14) on every invocation.

**Comment by flesler** [comment]
Agree, definitely a seed, not a salt.

**Comment by dylang** [comment]
Thanks @jamesrom and @flesler.
