### ISSUE TITLE
Return strings with specific length

### ISSUE THREAD

**Issue by gbuszmicz** [dylang/shortid#35]
Is there a way to specify the length of the string to generate?
Something like "len:10" and all strings generated are 10 chars long.
Great work by the way!!
Thanks!

**Comment by dylang** [comment]
Thanks for your question @gbuszmicz. This is not possible to make them *shorter* because they might not be unique, but you could add characters to generated ids to make them *longer*, as long as you are including a character to separate the generated id and the "extra characters" you are adding. This is not something this library does.

**Comment by hustcer** [comment]
@dylang So how to make it longer? I need longer ids for some cases. Thanks.
