### ISSUE TITLE
Generate id asynchronously 

### ISSUE THREAD

**Issue by Johnchristian99** [dylang/shortid#41]
Does shortid.generate() generates id synchronously? 

How to generate ids asynchronously? 
shortid.generate(function(err, id){
if(err) {
    console.log(err);
}
console.log(id);
})
 
Is it designed asynchronously or not?

**Comment by flesler** [comment]
They are sync, why would you want them async there's no advantage. The code doesn't take too long to generate one.

**Comment by Johnchristian99** [comment]
Even if it doesn't take too long still it is blocking.
in Node(just one thread) nothing should be blocking even if something doesn't blocks for too long.

**Comment by flesler** [comment]
You're referring to IO blocking, this is not IO.

**Comment by dylang** [comment]
There's no IO when generating id's.

**Comment by forty** [comment]
Hello,

I think this is indeed a real issue, crypto.randomBytes will block until enough entropy is available, which can take long when the system started recently. Using the synchronous version will freeze your server.
See nodejs documentation https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback
> The crypto.randomBytes() method will block until there is sufficient entropy. This should normally never take longer than a few milliseconds. The only time when generating the random bytes may conceivably block for a longer period of time is right after boot, when the whole system is still low on entropy.

I suggest either fixing it or at least mentioning the fact that crypto.randomBytes() is called synchronously so that someone does not use it on a production server by mistake.

**Comment by flesler** [comment]
I have been using this module for many months on production, on 10's of server at high-scale. No noticeable problem.

**Comment by forty** [comment]
For sure it probably depends on your OS, your traffic and how often you call the function. Still the documentation does say that the method blocks, and you should never block your one an only javascript thread if you care about performance.
Anyway no big deal, but one of our developer started using this module because he did not now about this blocking call, and I thought I'd warn you in case you cared.
