### ISSUE TITLE
Seed does not behave as I'd expect

### ISSUE THREAD

**Issue by NickHeiner** [dylang/shortid#45]
Maybe I'm just not understanding how this works, but I'd expect that if I set a consistent `seed` value, then I should always get the same sequence of ids. However, this is not what I observe.

```
λ node
> var shortid = require('shortid')
undefined
> shortid.seed('foo')
{ [Function: generate]
  generate: [Circular],
  seed: [Function: seed],
  worker: [Function: worker],
  characters: [Function: characters],
  decode: [Function: decode],
  isValid: [Function: isShortId] }
> shortid.generate()
'lMojA5yu'
> shortid.generate()
'l0VzAliK'
> shortid.generate()
'RghpzAliK'
> 
(^C again to quit)
> 
λ node
> var shortid = require('shortid')
undefined
> shortid.seed('foo')
{ [Function: generate]
  generate: [Circular],
  seed: [Function: seed],
  worker: [Function: worker],
  characters: [Function: characters],
  decode: [Function: decode],
  isValid: [Function: isShortId] }
> shortid.generate()
'R0U445ie' // expected 'lMojA5yu', since that was the first result last time
> shortid.generate()
'50pkQBye' // expected 'l0VzAliK', since that was the second result last time
> shortid.generate()
'Rw19kk52e' // expected 'RghpzAliK', since that was the third result last time
> 
```

I'm using node `v0.12.7` and `shortid@2.2.2`. 

Am I just misunderstanding something?

Possibly related: https://github.com/dylang/shortid/issues/19

**Comment by dylang** [comment]
Yes, there's more to it.

The seed is used to shuffle the order of the alphabet, not shuffle the characters selected. 

About half of the data in each string is randomly generated noise to avoid predictability, and about a quarter is related to the number of seconds since the `version`'s epoch (not the unix epoch, that number is too big). This way `shortid` can be used on many servers writing to the same database without concern about duplication even if they aren't all unique cluster id's. 

If you know the `seed` you an use the [decode function](https://github.com/dylang/shortid/blob/master/lib/decode.js) to get some of the metadata stored in the id back out.

**Comment by NickHeiner** [comment]
That makes sense. If one were interested in supporting my use case of having seeds fully determine the output, one could use a seedable random number generator like https://www.npmjs.com/package/alea.
