### ISSUE TITLE
grunt-cli is in dependencies, should be in devDependencies

### ISSUE THREAD

**Issue by apaatsio** [dylang/shortid#52]
I guess the title says it. grunt-cli should be in devDependencies.

Moreover, global installation is the preferred method for grunt-cli. npm install will give warning each time if you add it as dependency.

```
npm WARN prefer global grunt-cli@0.1.13 should be installed with -g

**Comment by dylang** [comment]
Thanks @apaatsio! I just pushed a new version with `grunt-cli` moved to devDep. The reason I do that instead of installing globally is because I switch between node versions frequently and don't want to have to keep re-installing `grunt-cli`. This way, I can just use `npm run <cmd>` to access grunt.
