### ISSUE TITLE
Is it possible to reduce the size of shortID

### ISSUE THREAD

**Issue by pravin-d** [dylang/shortid#60]
I'm using this lib for sending otp over sms. I wanted to know if its possible to change the shortid size from 7 - 14 to something like 4 - 6 ? This would really be helpful for sending over sms

**Comment by aamistak** [comment]
I'm also interested in this functionality

**Comment by mariangibala** [comment]
It's impossible due to duplication risk. #39

**Comment by Natim** [comment]
**What are the number of ids that can be generated safely with sortID?**

If we use a fixed length of 8 characters (6 bytes): we have 62^8 possibilities (source: http://stackoverflow.com/a/10859589/186202)

If you are generating ids from 2 to 6 characters you know have (62^4 + 62^5 + 62^6) which is 3782 times less combinations.

All of this depends of the number of records you will create in your collection that are not supposed to share the same id.

Here is a little Python script that help you calculate the probability of collision (based on [this article](http://preshing.com/20110504/hash-collision-probabilities/))

```Python
import math
N = 62**8
k = 1000000
probUnique = 1.0

probUnique = probUnique * (N - (k - 1)) / N
print k, 1 - probUnique, 1 - math.exp(-0.5 * k * (k - 1) / N)
```

N is the number of combinations and k the number of ids you will generate in your collection lifetime.

If you are sharing your phone address book, you can says that you are unlikely to have more that 20000 contacts.

The probability of getting twice the same id for you contact with an id between 4 and 6 is 0.0035
We means that 4 times on 1000 shortId generation you are likely to have collision (to get twice the same). That's a lot.

With a fixed 8 characters length you will have: less than 1 collision per 100000 and since you are generating 5 times less ids you have good chance not to have any collisions.

Now if we are generating ids from 7 to 14 characters we have this number of possibilities: 

    62^7 + 62^8 + 62^9 + 62^10 + 62^11 + 62^12 + 62^13 + 62^14 = 12605077130307592572754560

With 20000 records it is unlikely that you will have any collisions.

You have to get to a three hundred millions of records to get the same collision probability as you have got with the 4-6 lengths ids.

While you reach it with 1 million records with a fixed 8 characters string.

**Comment by Natim** [comment]
Except that it is 64 characters and not 62 but feel free to redo the calculations.

**Comment by Natim** [comment]
So basically it should be fine to use shortIDs with 4-6 if you can assert that you will never have more than 200 records in your collection which is really low.

**Comment by Natim** [comment]
For the record here is a piece of Python script that I use to generate shortIDs:
It is based on cryptographic random bytes.

```python
import base64
import os
import random


def shortid(nb_bytes=6):
    return base64.urlsafe_b64encode(
        os.urandom(nb_bytes)).decode('utf-8').rstrip('=')


class ShortId(object):
    # From 7 to 14 characters: Up to 64^7 + 64^8 + ... + 64^14
    def __init__(self, min_bytes=5, max_bytes=10):
        self.min_bytes = min_bytes
        self.max_bytes = max_bytes

    def generate(self, nb_bytes=None):
        if not nb_bytes:
            random.seed = os.urandom(1024)
            nb_bytes = random.randint(self.min_bytes, self.max_bytes)
        return shortid(nb_bytes)
```

**Comment by Natim** [comment]
For the record here is a piece of NodeJS that I use to generate shortIDs:

```js
"use strict";

var randomBytes = require('crypto').randomBytes;

/**
 * Return a shortID of nbBytes. (default: 6)
 */
function shortID(nbBytes) {
  if (typeof nbBytes === 'undefined') {
    nbBytes = 6;
  }

  return randomBytes(nbBytes).toString('base64').replace(/=+$/g, "");
}

/**
 * Generate a shortID of lenght between minBytes and maxBytes. (default: 5-10)
 */
function generate(minBytes, maxBytes) {
  var nbBytes;

  if (typeof minBytes === 'undefined') {
    minBytes = 5;
  }

  if (typeof maxBytes === 'undefined') {
    maxBytes = 10;
  }

  nbBytes = Math.floor(Math.random() * (maxBytes - minBytes +1)) + minBytes;

  return shortID(nbBytes);
}

module.exports = {
  shortID: shortID,
  generate: generate
};
```

**Comment by Natim** [comment]
Note for myself: base64 encode of a bytes string doesn't actually generate all 64 combinations for all characters so the two above code will not generate the 64**(string length) we were talking about before.

    64**7 == 4398046511104

while

    5 bytes == 2**(8*5+1) -1 == 2199023255551

So using a random choice of the alphabet would generate more combinations.
However I believe the math are correct.

**Comment by Natim** [comment]
I asked [the question on Stackoverflow](http://stackoverflow.com/questions/35723212/how-to-use-urandom-to-generate-all-possible-base64-characters) and I will update the above code with the correct solution.

**Comment by Natim** [comment]
The above code has been updated.
