### ISSUE TITLE
remove crypto dependency

### ISSUE THREAD

**Issue by nikkwong** [dylang/shortid#92]
This is intended to be used in browsers, but loaders like System can't import the crypto module. Can we remove the dep on ```crypto```?

**Comment by ai** [comment]
We have special hack for `webpack` to change `./lib/random/random-byte.js` in browser build https://github.com/dylang/shortid/blob/master/package.json#L33

As result browser build doesn’t use `crypto` https://github.com/dylang/shortid/blob/master/lib/random/random-byte-browser.js

What exactly problem do you have. Show you tools and error output. Maybe this file replacing system doesn’t work for you?

We can’t just remove `crypto`, because we use it to generate random bytes in Node.js https://github.com/dylang/shortid/blob/master/lib/random/random-byte.js

**Comment by nikkwong** [comment]
That's great, but it doesn't work for other module loaders like ```SystemJS```

**Comment by ai** [comment]
I understand you. But you need to open issue in SystemJS.

Or do you know any solution to keep Node.js version correctly​ too?

**Comment by nikkwong** [comment]
What makes this a systemJS issue? AFAIK there's no way to just "ignore" a require call. The best you can do is shim it to another dependency, but ```crypto``` lives on the window—and I don't think it's ```system```'s responsibility to cover a weird use case like having a require call map to something on the window.

From the issues I've read I think people have expressed interest in doing some type of light environment checking before deciding how to load the ```crypto``` dependency. That could eliminate the webpack hack. Is this not something we should support?

**Comment by ai** [comment]
Why it is SystemJS issue:

1. There are many cases, where you can’t write code for Node.js and browser. For example, in my PostCSS `fs` is used.
2. This is why good Node.js→browser compiler should provide feature to replace some Node.js file to browser file.
3. Webpack and Browerify already do it.
4. Having `if ( isBrowsers() ) { require('') }` will increase file size. So webpack and Browserify users will have bigger JS files.

What you can do:

1. You should ask SystemJS community. There are many npm packages with `browsers` hack. It is a normal practice. So they should know some workaround.
2. You can replace `require()` call outside SystemJS. Add some `prepareForBrowser` step to you build process and replace `require("./lib/random/random-byte.js")` to `require("./lib/random/random-byte-browser.js")`.

What do you think about it?
